# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jeulliot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/21 10:10:10 by jeulliot          #+#    #+#              #
#    Updated: 2022/02/24 22:54:02 by jeulliot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	= ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
		  ft_toupper.c ft_tolower.c ft_strlen.c ft_strncmp.c ft_atoi.c \
		  ft_bzero.c ft_strlcpy.c ft_strchr.c ft_strrchr.c ft_strnstr.c \
		  ft_strlcat.c ft_substr.c ft_strjoin.c ft_split.c ft_itoa.c \
		  ft_strmapi.c ft_striteri.c ft_strtrim.c ft_putchar_fd.c \
		  ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_memset.c \
		  ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_calloc.c \
		  ft_strdup.c

BSRCS	= ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c \
		  ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
		  ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

OBJS	= ${SRCS:.c=.o}

BOBJS	= ${BSRCS:.c=.o}

NAME	= libft.a

CC	= gcc

RM	= rm -f

CFLAGS	= -Wall -Wextra -Werror 

all:	$(NAME)

$(NAME):	${OBJS}
			ar rc $(NAME) ${OBJS}	

.c.o:
	${CC} ${CFLAGS} -c ${LDFLAGS} $< -o ${<:.c=.o}

clean:
	${RM} ${OBJS}
	${RM} ${BOBJS}

fclean:	clean
	${RM} ${NAME}
	${RM} ${BONUS}

re:	fclean all

bonus: ${BOBJS} ${OBJS}
	ar rc ${NAME} ${OBJS} ${BOBJS}
